name: CI PHP

on:
  push:
    branches:
        - main
        - dev
    paths:
      - 'php/**'
  pull_request:
    branches:
        - main
        - dev
    paths:
      - 'php/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # ou a versão desejada do PHP

      - name: Install dependencies
        working-directory: ./php
        run: |
          composer install

      - name: Run tests with PHPUnit
        working-directory: ./php
        run: |
          vendor/bin/phpunit --configuration phpunit.xml
